### ISSUE TITLE
Need Volunteers

### ISSUE THREAD

**Issue by rhnvrm** [planetGSoC/planetGSoC.github.io#1]
If you want to volunteer for helping in maintaining planetGSoC, please comment below and I will add you to the Volunteer Team

Volunteers will be responsible for
- Accepting PRs to the list
- Redeploying the OpenShift server with the updated list
- Helping with improving PlanetGSoC

**Comment by pandeydivesh15** [comment]
Add me☺

**Comment by gmarcos87** [comment]
Me to!

**Comment by suthagar23** [comment]
Mee too

**Comment by abs51295** [comment]
Me too!

**Comment by meets2tarun** [comment]
Sure, add me please!

**Comment by rhnvrm** [comment]
@pandeydivesh15 @gmarcos87 @suthagar23 @abs51295 @meets2tarun Thanks! Have added you to the Volunteer team! :+1:

**Comment by meets2tarun** [comment]
@rhnvrm Thank you, I will try my best to work for the repo.
I think we should now close this issue?
